package webscraping.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static webscraping.Queries.*;
// Generated by ComTest END
import java.io.IOException; 
import java.net.MalformedURLException; 
import java.net.ProtocolException; 
import java.net.URI; 
import java.net.http.HttpClient; 
import java.net.http.HttpRequest; 
import java.net.http.HttpResponse; 

/**
 * Test class made by ComTest
 * @version 2023.02.25 17:01:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class QueriesTest {



  // Generated by ComTest BEGIN
  /** 
   * testFinnaQuery45 
   * @throws MalformedURLException when error
   */
  @Test
  public void testFinnaQuery45() throws MalformedURLException {    // Queries: 45
    String s = finnaQuery("9789511297444", "isbn"); 
    String[] json = s.split("\\{"); 
    assertEquals("From: Queries line: 53", "\"resultCount\":1,\"records\":[", json[1]); 
    assertEquals("From: Queries line: 54", " value : 1 /Book /Book / , translated : Book }], id : anders.1500431 , images :[], languages :[ fin ], nonPresenterAuthors :[", json[6].replace('"', ' ').replace('\\', ' '));
    String finna = "anders.1654424"; 
    String s2 = finnaQuery("anders.1654424", "finna"); 
    String[] json2 = s2.split(System.lineSeparator()); 
  } // Generated by ComTest END
}