package webscraping.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import org.jsoup.nodes.Document;
import org.junit.*;
import webscraping.*;
import java.util.ArrayList;
import static org.junit.Assert.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 07:41:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class YKLQueryTest {



  // Generated by ComTest BEGIN
  /** 
   * testYKLQuery23 
   * @throws IOException when error
   * @throws InterruptedException when error
   */
  @Test
  public void testYKLQuery23() throws IOException, InterruptedException {    // YKLQuery: 23
    ArrayList<String> arr = new ArrayList<String>(); 
    YKLQuery.recursiveFintoQuery("1", arr); 
    int len = arr.size(); 
    assertEquals("From: YKLQuery line: 34", "1 FILOSOFIA. PSYKOLOGIA. RAJATIETO. TIEDEOPPI", arr.get(len - 1)); 
    assertEquals("From: YKLQuery line: 35", 43, len); 
    arr.clear(); len = 0; 
    YKLQuery.recursiveFintoQuery("100", arr); 
    assertEquals("From: YKLQuery line: 38", 0, arr.size()); 
    YKLQuery.recursiveFintoQuery("abxsd", arr); 
    assertEquals("From: YKLQuery line: 40", 0, arr.size()); 
  } // Generated by ComTest END
}