package kirtika.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 09:24:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BooksTest {



  // Generated by ComTest BEGIN
  /** testResizeArray74 */
  @Test
  public void testResizeArray74() {    // Books: 74
    Books books = new Books(true); 
    Book book = new Book(); 
    book.setOdysseia(); 
    assertEquals("From: Books line: 78", 10, books.getItemsLength()); 
    books.addItems(book, 10); 
    assertEquals("From: Books line: 80", 10, books.getAmt()); 
    assertEquals("From: Books line: 81", 10, books.getItemsLength()); 
    books.addBook(book); 
    assertEquals("From: Books line: 83", 20, books.getItemsLength()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testDeleteBook100 */
  @Test
  public void testDeleteBook100() {    // Books: 100
    Books books = new Books(true); 
    Book book1 = new Book(); 
    book1.setOdysseia(); 
    books.addItems(book1, 3); 
    Book book2 = new Book(); 
    book2.setOdysseia(); 
    books.addBook(book2); 
    assertEquals("From: Books line: 108", book2, books.get(3)); 
    books.addItems(book1, 3); 
    books.deleteBook(book2); 
    assertEquals("From: Books line: 111", book1, books.get(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetBookNotes135 
   * @throws IOException when error
   */
  @Test
  public void testGetBookNotes135() throws IOException {    // Books: 135
    Books books = new Books(true); 
    Book book = new Book(); 
    book.setOdysseia(); 
    books.addBook(book); 
    assertEquals("From: Books line: 143", "", books.getBookNotes(book)); 
    books.saveBookNotes(book, "Nymfit najadit Zeun tyttäret!"); 
    assertEquals("From: Books line: 145", "Nymfit najadit Zeun tyttäret!", books.getBookNotes(book)); 
    books.deleteBookNotes(book); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testDeleteBookNotes176 
   * @throws IOException when error
   */
  @Test
  public void testDeleteBookNotes176() throws IOException {    // Books: 176
    Books books = new Books(); 
    Book book = new Book(); 
    book.setOdysseia(); 
    assertEquals("From: Books line: 181", false, books.deleteBookNotes(book)); 
    String s = books.getBookNotes(book); 
    assertEquals("From: Books line: 183", true, books.deleteBookNotes(book)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAddBook236 */
  @Test
  public void testAddBook236() {    // Books: 236
    Books kirjat = new Books(); 
    Book ody = new Book(); 
    int x = kirjat.getAmt(); 
    kirjat.addBook(ody); 
    assertEquals("From: Books line: 241", x + 1, kirjat.getAmt()); 
  } // Generated by ComTest END
}