package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.28 15:34:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenretTest {



  // Generated by ComTest BEGIN
  /** testEtsiYklKuvaus62 */
  @Test
  public void testEtsiYklKuvaus62() {    // Genres: 62
    Genres genres = new Genres("84.2|Suomalainen kertomakirjallisuus"); 
    assertEquals("From: Genres line: 64", "Suomalainen kertomakirjallisuus", genres.getYklDesc("84.2")); 
    assertEquals("From: Genres line: 65", "Ei tiedetä", genres.getYklDesc("67")); 
  } // Generated by ComTest END
}