package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.28 15:34:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenretTest {



  // Generated by ComTest BEGIN
  /** testEtsiYklKuvaus62 */
  @Test
  public void testEtsiYklKuvaus62() {    // Genret: 62
    Genret genret = new Genret("84.2|Suomalainen kertomakirjallisuus"); 
    assertEquals("From: Genret line: 64", "Suomalainen kertomakirjallisuus", genret.etsiYklKuvaus("84.2")); 
    assertEquals("From: Genret line: 65", "Ei tiedetä", genret.etsiYklKuvaus("67")); 
  } // Generated by ComTest END
}