package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kirtika.Genre.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.25 11:50:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenreTest {



  // Generated by ComTest BEGIN
  /** testGenre26 */
  @Test
  public void testGenre26() {    // Genre: 26
    Genre genre = new Genre("84.2|Suomalainen kertomakirjallisuus"); 
    assertEquals("From: Genre line: 28", "84.2", genre.getGenreId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString90 */
  @Test
  public void testToString90() {    // Genre: 90
    Genre genre = new Genre("84.2|Suomalainen kertomakirjallisuus"); 
    assertEquals("From: Genre line: 92", "84.2 Suomalainen kertomakirjallisuus", genre.toString()); 
  } // Generated by ComTest END
}