package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 07:55:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenresTest {



  // Generated by ComTest BEGIN
  /** testAddGenre63 */
  @Test
  public void testAddGenre63() {    // Genres: 63
    Genres g = new Genres("84.2|Suomalainen kertomakirjallisuus"); 
    g.addGenre("76.7 Paperitaide"); 
    assertEquals("From: Genres line: 66", 2, g.getGenreCount()); 
    Genre genre = g.getGenre(1); 
    assertEquals("From: Genres line: 68", "Paperitaide", genre.getGenreDesc()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testDeleteGenre80 */
  @Test
  public void testDeleteGenre80() {    // Genres: 80
    Genres g = new Genres("84.2|Suomalainen kertomakirjallisuus"); 
    g.addGenre("57.1 Putkilokasvit"); 
    g.addGenre("61.3 Ohjelmointi. Ohjelmointikielet"); 
    assertEquals("From: Genres line: 84", 3, g.getGenreCount()); 
    Genre a = g.getGenre(2); 
    g.deleteGenre(a); 
    a = g.getGenre(1); 
    g.deleteGenre(a); 
    a = g.getGenre(0); 
    g.deleteGenre(a); 
    assertEquals("From: Genres line: 91", 0, g.getGenreCount()); 
    g.deleteGenre(a);  // nothing happens
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetYklDesc187 */
  @Test
  public void testGetYklDesc187() {    // Genres: 187
    Genres genret = new Genres("84.2|Suomalainen kertomakirjallisuus"); 
    assertEquals("From: Genres line: 189", "Suomalainen kertomakirjallisuus", genret.getYklDesc("84.2")); 
    assertEquals("From: Genres line: 190", null, genret.getYklDesc("67")); 
  } // Generated by ComTest END
}