package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.11 11:27:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GenresTest {



  // Generated by ComTest BEGIN
  /** testGetYklDesc67 */
  @Test
  public void testGetYklDesc67() {    // Genres: 67
    Genres genret = new Genres("84.2|Suomalainen kertomakirjallisuus"); 
    assertEquals("From: Genres line: 69", "Suomalainen kertomakirjallisuus", genret.getYklDesc("84.2")); 
    assertEquals("From: Genres line: 70", "Unknown", genret.getYklDesc("67")); 
  } // Generated by ComTest END
}