package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.20 11:38:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testGetIsbn74 */
  @Test
  public void testGetIsbn74() {    // Book: 74
    Book kirja1 = new Book(); 
    kirja1.setOdysseia(); 
    assertEquals("From: Book line: 77", "9789511318866", kirja1.getIsbn()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetKirjaId88 */
  @Test
  public void testSetKirjaId88() {    // Book: 88
    Book kirja1 = new Book(); 
    Book kirja2 = new Book(); 
    int n1 = kirja1.setBookId(); 
    int n2 = kirja2.setBookId(); 
    assertEquals("From: Book line: 93", n2 - 1, n1); 
  } // Generated by ComTest END
}