package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.20 11:38:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testGetIsbn74 */
  @Test
  public void testGetIsbn74() {    // Kirja: 74
    Kirja kirja1 = new Kirja(); 
    kirja1.setOdysseia(); 
    assertEquals("From: Kirja line: 77", "9789511318866", kirja1.getIsbn()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetKirjaId88 */
  @Test
  public void testSetKirjaId88() {    // Kirja: 88
    Kirja kirja1 = new Kirja(); 
    Kirja kirja2 = new Kirja(); 
    int n1 = kirja1.setKirjaId(); 
    int n2 = kirja2.setKirjaId(); 
    assertEquals("From: Kirja line: 93", n2 - 1, n1); 
  } // Generated by ComTest END
}