package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.20 11:38:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {


  // Generated by ComTest BEGIN
  /** testLisaa30 */
  @Test
  public void testLisaa30() {    // Kirjat: 30
    Kirjat kirjat = new Kirjat(); 
    Kirja ody = new Kirja(); 
    assertEquals("From: Kirjat line: 33", 0, kirjat.getLkm()); 
    kirjat.lisaa(ody); 
    assertEquals("From: Kirjat line: 35", 1, kirjat.getLkm()); 
  } // Generated by ComTest END
}