package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.10 14:31:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** testLisaa99 */
  @Test
  public void testLisaa99() {    // Kirjat: 99
    Kirjat kirjat = new Kirjat(); 
    Kirja ody = new Kirja(); 
    int x = kirjat.getLkm(); 
    kirjat.lisaa(ody); 
    assertEquals("From: Kirjat line: 104", x + 1, kirjat.getLkm()); 
  } // Generated by ComTest END
}