package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.11 09:42:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirtikaTest {


  // Generated by ComTest BEGIN
  /** testGetBookInfo74 */
  @Test
  public void testGetBookInfo74() {    // Kirtika: 74
    Kirtika kirtika = new Kirtika(); 
    String[] s = kirtika.getBookInfo(1); 
    assertEquals("From: Kirtika line: 77", "suomi", s[1]); 
  } // Generated by ComTest END
}