package kirtika.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END
import webscraping.FinnaHaku.BookNotFoundException;

/**
 * Test class made by ComTest
 * @version 2023.04.11 10:41:26 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirtikaTest {



  // Generated by ComTest BEGIN
  /** testGetBookInfo76 */
  @Test
  public void testGetBookInfo76() {    // Kirtika: 76
    Kirtika kirtika = new Kirtika(); 
    String[] s = kirtika.getBookInfo(1); 
    assertEquals("From: Kirtika line: 79", "suomi", s[1]); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testFetchFinnaData111 
   * @throws BookNotFoundException when error
   */
  @Test
  public void testFetchFinnaData111() throws BookNotFoundException {    // Kirtika: 111
    Kirtika kirtika = new Kirtika(); 
    ArrayList list = kirtika.fetchFinnaData("9789524953856"); 
    assertEquals("From: Kirtika line: 116", "Talous ja moraali", list.get(0)); 
    assertEquals("From: Kirtika line: 117", "Korkman, Sixten, 1948- kirjoittaja; ", list.get(1)); 
    assertEquals("From: Kirtika line: 118", "fin; ", list.get(2)); 
  } // Generated by ComTest END
}