package kirtika.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.11 10:01:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirtikaTest {



  // Generated by ComTest BEGIN
  /** testGetBookInfo75 */
  @Test
  public void testGetBookInfo75() {    // Kirtika: 75
    Kirtika kirtika = new Kirtika(); 
    String[] s = kirtika.getBookInfo(1); 
    assertEquals("From: Kirtika line: 78", "suomi", s[1]); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testFetchFinnaData102 */
  @Test
  public void testFetchFinnaData102() {    // Kirtika: 102
    Kirtika kirtika = new Kirtika(); 
    ArrayList list = kirtika.fetchFinnaData("9789524953856"); 
    assertEquals("From: Kirtika line: 106", "Talous ja moraali", list.get(0)); 
    assertEquals("From: Kirtika line: 107", "Korkman, Sixten, 1948- kirjoittaja; ", list.get(1)); 
    assertEquals("From: Kirtika line: 108", "fin; ", list.get(2)); 
  } // Generated by ComTest END
}