package kirtika.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 09:18:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LoansTest {



  // Generated by ComTest BEGIN
  /** testDeleteLoan127 */
  @Test
  public void testDeleteLoan127() {    // Loans: 127
    Loans loans = new Loans(true); 
    Book book1 = new Book(); 
    book1.setOdysseia(); 
    Book book2 = new Book(); 
    book2.setOdysseia(); 
    loans.addBookLoan(book1, "Matti"); 
    loans.addBookLoan(book2, "Maija"); 
    assertEquals("From: Loans line: 136", 2, loans.getLoansAmt()); 
    loans.deleteLoan(2); 
    assertEquals("From: Loans line: 138", 1, loans.getLoansAmt()); 
    loans.deleteLoan(1); 
    assertEquals("From: Loans line: 140", 0, loans.getLoansAmt()); 
  } // Generated by ComTest END
}