package kirtika.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import java.io.FileNotFoundException;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import kirtika.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 08:57:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LoansTest {



  // Generated by ComTest BEGIN
  /** testDeleteLoan157 */
  @Test
  public void testDeleteLoan157() {    // Loans: 157
    Loans lo = new Loans(true); 
    Book book1 = new Book(); 
    book1.setOdysseia(); 
    Book book2 = new Book(); 
    book2.setOdysseia(); 
    Book book3 = new Book(); 
    book3.setOdysseia(); 
    lo.addBookLoan(book1, "Matti"); 
    lo.addBookLoan(book2, "Maija"); 
    lo.addBookLoan(book3, "Mikko"); 
    int size = lo.getLoansAmt(); 
    Loan l = lo.getLoan(size-1); 
    int id = l.getLoanId(); 
    lo.deleteLoan(id); 
    assertEquals("From: Loans line: 173", size-1, lo.getLoansAmt()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testSaveBookLoans194 
   * @throws FileNotFoundException when error
   * @throws IOException when error
   */
  @Test
  public void testSaveBookLoans194() throws FileNotFoundException, IOException {    // Loans: 194
    Loans loans = new Loans(true, "src/data/testlainat.dat"); 
    loans.createNewFile(); 
    Book book1 = new Book(); 
    Book book2 = new Book(); 
    book1.setOdysseia(); 
    book2.setOdysseia(); 
    loans.addBookLoan(book1, "Matti"); 
    loans.addBookLoan(book2, "Maija"); 
    loans.saveBookLoans(); 
    loans.deleteLoansFile(); 
  } // Generated by ComTest END
}