package utils.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static utils.StringSanitizer.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.10 15:23:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class StringSanitizerTest {



  // Generated by ComTest BEGIN
  /** testReplaceNordicChars14 */
  @Test
  public void testReplaceNordicChars14() {    // StringSanitizer: 14
    String input = "Älä höpötä, Øystein! Örjan on väärässä."; 
    assertEquals("From: StringSanitizer line: 16", "Ala hopota, Oystein! Orjan on vaarassa.", replaceNordicChars(input)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testReplaceSpecialChars35 */
  @Test
  public void testReplaceSpecialChars35() {    // StringSanitizer: 35
    String input = "Ala hopota, Oystein! Orjan on vaarassa."; 
    assertEquals("From: StringSanitizer line: 37", "AlahopotaOysteinOrjanonvaarassa", replaceSpecialChars(input)); 
  } // Generated by ComTest END
}