package utils.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static utils.StringUtils.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.14 08:39:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class StringUtilsTest {



  // Generated by ComTest BEGIN
  /** testMatchesGenreFormat15 */
  @Test
  public void testMatchesGenreFormat15() {    // StringUtils: 15
    assertEquals("From: StringUtils line: 16", true, matchesGenreFormat("84.2 Suomalainen kaunokirjallisuus")); 
    assertEquals("From: StringUtils line: 17", false, matchesGenreFormat("Suomalainen kaunokirjallisuus")); 
    assertEquals("From: StringUtils line: 18", false, matchesGenreFormat("0")); 
    assertEquals("From: StringUtils line: 19", false, matchesGenreFormat("84.2Suomalainen kaunokirjallisuus")); 
    assertEquals("From: StringUtils line: 20", true, matchesGenreFormat("84.2.3 Suomalainen kaunokirjallisuus")); 
    assertEquals("From: StringUtils line: 21", false, matchesGenreFormat("84,2 Suomalainen kaunokirjallisuus")); 
    assertEquals("From: StringUtils line: 22", true, matchesGenreFormat("84.2.2 Suomalainen kaunokirjallisuus, Waltarin kirjat")); 
    assertEquals("From: StringUtils line: 23", false, matchesGenreFormat("0000")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testReplaceNordicChars37 */
  @Test
  public void testReplaceNordicChars37() {    // StringUtils: 37
    String input = "Älä höpötä, Øystein! Örjan on väärässä."; 
    assertEquals("From: StringUtils line: 39", "Ala hopota, Oystein! Orjan on vaarassa.", replaceNordicChars(input)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testReplaceSpecialChars58 */
  @Test
  public void testReplaceSpecialChars58() {    // StringUtils: 58
    String input = "Ala hopota, Oystein! Orjan on vaarassa."; 
    assertEquals("From: StringUtils line: 60", "AlahopotaOysteinOrjanonvaarassa", replaceSpecialChars(input)); 
  } // Generated by ComTest END
}